# Generated by Django 4.2.11 on 2024-04-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicInformationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField()),
                ("age", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PhotoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("image", models.ImageField(upload_to="photos/")),
            ],
        ),
        migrations.CreateModel(
            name="SkillModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("level", models.PositiveBigIntegerField(default=50)),
            ],
        ),
    ]
