# Generated by Django 4.2.11 on 2024-04-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='descriptions',
            new_name='description',
        ),
    ]
